name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]  # or main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        # This creates the 'out' directory
        run: npm run build

      - name: Create .nojekyll file
        # Create an empty .nojekyll file in the 'out' directory
        # so GitHub Pages serves the site correctly.
        run: touch out/.nojekyll